name: ngrok-ssh
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: free -m
      - run: lscpu
      - run: useradd ${{ secrets.NGROK_PASSWORD }}
      - run: echo ${{ secrets.NGROK_PASSWORD }} | passwd ${{ secrets.NGROK_USER }} --stdin
      - run: curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok
      - run: ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}
      - run: ngrok tcp 22
